sudo: required
dist: trusty

language: node_js

addons:
 firefox: latest
 apt:
  sources:
  - google-chrome
  - sourceline: "deb http://deb.opera.com/opera/ stable non-free"
  packages:
  - google-chrome-stable
  - opera-stable

node_js:
 - node

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
