language: node_js

sudo: required
dist: trusty

os:
 - linux

addons:
 firefox: latest
 apt:
  sources:
  - google-chrome
  - sourceline: "deb http://deb.opera.com/opera/ stable non-free"
  packages:
  - google-chrome-stable
  - opera-stable

node_js:
 - node
 - "7"
 - "6"

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
   fi

after_script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    cat ./coverage/*irefox*/lcov.info | ./node_modules/coveralls/bin/coveralls.js;
   fi
