sudo: required
dist: trusty

language: node_js

addons:
 firefox: latest
 apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable

node_js:
 - node

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
